apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    app: api
    cost-center: e-commerce
    team: shopping-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities:
              add:
                - ALL
          resources:
            limits:
              memory: 512Mi # TODO: Set this to the maximum amount of memory you want your workload to use
              cpu: 100m # TODO: Set this to the maximum amount of CPU you want your workload to use
            requests:
              cpu: 100m # TODO: Set this to the amount of CPU you want to reserve for your workload
              memory: 512Mi # TODO: Set this to the amount of Memory you want to reserve for your workload
