apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    cost-center: e-commerce
    team: shopping-cart
    owner: jp@example.com
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:1.36.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: true
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          imagePullPolicy: Always
          livenessProbe:
            # TODO: Change the livenessProbe setting to reflect your application's health
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            # TODO: Change the readinessProbe setting to reflect your application's readiness to serve traffic
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
